=== elenaABSauces/Proyecto1920_LMSGI_EAB/1920_LMSGI_EAB/ud06/PizzeriaPasoFinal/public_html/datos/PizzeriaXml.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Elementos complejos-->
    <xs:element name="restaurante" type="RESTAURANTE"/>
    
    
    <!--Elementos simples-->
    
    <!--Tipos para elementos, simples y complejos-->
       
    <!--Tipo RESTAURANTE es el tipo del elemento raiz-->
    <xs:complexType name="RESTAURANTE">
        <xs:sequence>
            <xs:element name="pizzas" type="PIZZAS"/>
            <xs:element name="entrantes" type="ENTRANTE"/>
            <xs:element name="postres" type="POSTRES"/>
            <xs:element name="bebidas" type="BEBIDAS"/>
        </xs:sequence>
    </xs:complexType>
       
    <xs:complexType name="PIZZAS">
        <xs:sequence>
            <xs:element name="pizza" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="precio" type="DECIMAL"/>
                    <xs:element name="ingredientes">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="ingrediente" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="masa" type="MASA"/>
                    <xs:element name="tamano" type="TAMANO"/>
                    <xs:element name="foto" type="FOTO"/>
                    <xs:element name="link">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="www.thecreatorspizza.es/[a-z0-9]*"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    </xs:sequence>
                    <xs:attribute ref="codPizza" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    
    <!--Tipos para subtipos de pizza-->
    <xs:complexType name="MASA">
        <xs:attribute ref="tipoMasa" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="TAMANO">
        <xs:attribute ref="tipoTamano" use="required"/>
    </xs:complexType>

    <xs:complexType name="FOTO">
        <xs:attribute ref="tipoFoto" use="required"/>
    </xs:complexType>

    <!--Fin de subtipos de la pizza-->
    <xs:complexType name="ENTRANTE">
        <xs:sequence>
            <xs:element name="entrante" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="precio" type="DECIMAL"/>
                        <xs:element name="cantidad">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:positiveInteger">
                                        <xs:attribute ref="tipoCantidad" use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="POSTRES">
        <xs:sequence>
            <xs:element name="postre" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute ref="sabor" use="optional" default="oreo"/>
                                    </xs:extension> 
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="precio" type="DECIMAL"/>
                    </xs:sequence>
                    <xs:attribute ref="codigoPostre" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="BEBIDAS">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="agua" type="AGUA"/>
            <xs:element name="cerveza" type="CERVEZA"/>
            <xs:element name="refresco" type="REFRESCO"/>
        </xs:choice>
    </xs:complexType>
    
    <!--Comun para los tres elementos -->
    <xs:complexType name="GENERAL">
        <xs:sequence>
            <xs:element name="precio" type="DECIMAL"/>
            <xs:element name="cantidad" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute ref="tipo" default="frio" use="optional"/>
    </xs:complexType>
    
    <!--Elementos de bebidas-->
    <xs:complexType name="AGUA">
        <xs:complexContent>
            <xs:extension base="GENERAL">
                <xs:attribute ref="tipoAgua" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="CERVEZA">
        <xs:complexContent>
            <xs:extension base="GENERAL">
                <xs:attribute ref="tipoCerveza" use="required"/>
                <xs:attribute ref="marcaCerveza" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="REFRESCO">
        <xs:complexContent>
            <xs:extension base="GENERAL">
                <xs:attribute ref="marcaRefresco" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <!--Tipo para un decimal positivo-->
    <xs:simpleType name="DECIMAL">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--Atributos-->
    <xs:attribute name="codPizza">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="P0[1-9]"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
            
    <xs:attribute name="tipoMasa">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="fina"/>
                <xs:enumeration value="gruesa"/>
                <xs:enumeration value="pan"/>
                <xs:enumeration value="cuadrada"/>
                <xs:enumeration value="rellena"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
        
    <xs:attribute name="tipoTamano">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="pequena"/>
                <xs:enumeration value="mediana"/>
                <xs:enumeration value="familiar"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="tipoFoto">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="jpg"/>
                <xs:enumeration value="png"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="tipoCantidad">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="racion"/>
                <xs:enumeration value="unidad"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="sabor">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="oreo"/>
                <xs:enumeration value="coockie"/>
                <xs:enumeration value="kitkat"/>
                <xs:enumeration value="caramelo"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="codigoPostre">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:pattern value="[0][1-6]"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="tipo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="frio"/>
                <xs:enumeration value="tiempo"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="tipoAgua">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="mineral"/>
                <xs:enumeration value="sin_gas"/>
                <xs:enumeration value="con_gas"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="tipoCerveza">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="0.0"/>
                <xs:enumeration value="sin alcohol"/>
                <xs:enumeration value="normal"/>
                <xs:enumeration value="lagger"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="marcaCerveza">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="paulaner"/>
                <xs:enumeration value="superboock"/>
                <xs:enumeration value="keler"/>
                <xs:enumeration value="heineken"/>
                <xs:enumeration value="mahou"/>
                <xs:enumeration value="estrella"/>
                <xs:enumeration value="amstel"/>
                <xs:enumeration value="corona"/>
                <xs:enumeration value="voll_damm"/>
                <xs:enumeration value="buckler"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:attribute name="marcaRefresco">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="pepsi"/>
                <xs:enumeration value="cocacola"/>
                <xs:enumeration value="cocacola_light"/>
                <xs:enumeration value="kas_naranja"/>
                <xs:enumeration value="kas_limon"/>
                <xs:enumeration value="fanta_naranja"/>
                <xs:enumeration value="fanta_limon"/>
                <xs:enumeration value="7up"/>
                <xs:enumeration value="nestea"/>
                <xs:enumeration value="aquarius"/>
                <xs:enumeration value="redbull"/>
                <xs:enumeration value="bitter_kas"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
</xs:schema>

=== elenaABSauces/Proyecto1920_LMSGI_EAB/1920_LMSGI_EAB/ud06/PizzeriaPasoFinal/public_html/datos/PizzeriaXml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<restaurante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PizzeriaXml.xsd">
    <pizzas>
        <pizza codPizza="P01">
            <nombre>Dawers Rangers</nombre> 
            <precio>9</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>mozzarella</ingrediente>
                <ingrediente>champinon</ingrediente>
                <ingrediente>atun</ingrediente>
                <ingrediente>aceituna negra</ingrediente>
            </ingredientes>
            <masa tipoMasa="rellena"/>
            <tamano tipoTamano="familiar"/>
            <foto tipoFoto="png"/>
            <link>www.thecreatorspizza.es/dawersrangers</link>
        </pizza>
        <pizza codPizza="P02">
            <nombre>TheCreators</nombre> 
            <precio>7.5</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>mozzarella</ingrediente>
                <ingrediente>pina</ingrediente>
                <ingrediente>bacon</ingrediente>
                <ingrediente>aceituna verde</ingrediente>
            </ingredientes>
            <masa tipoMasa="cuadrada"/>
            <tamano tipoTamano="pequena"/>
            <foto tipoFoto="jpg"/>
            <link>www.thecreatorspizza.es/thecreators</link>
        </pizza>
        <pizza codPizza="P03">
            <nombre>La banda del patio</nombre> 
            <precio>6.5</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>mozzarella</ingrediente>
                <ingrediente>carne</ingrediente>
                <ingrediente>salsa barbacoa</ingrediente>
            </ingredientes>
            <masa tipoMasa="fina"/>
            <tamano tipoTamano="mediana"/>
            <foto tipoFoto="jpg"/>
            <link>www.thecreatorspizza.es/labandadelpatio</link>
        </pizza>
        <pizza codPizza="P04">
            <nombre>Heavy Afternoon</nombre> 
            <precio>8</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>queso cheddar</ingrediente>
                <ingrediente>atun</ingrediente>
                <ingrediente>maiz</ingrediente>
                <ingrediente>bacon</ingrediente>
            </ingredientes>
            <masa tipoMasa="gruesa"/>
            <tamano tipoTamano="mediana"/>
            <foto tipoFoto="jpg"/>
            <link>www.thecreatorspizza.es/heavyafternoon</link>
        </pizza>
        <pizza codPizza="P05">
            <nombre>Los Tildaos</nombre> 
            <precio>13</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>queso parmesano</ingrediente>
                <ingrediente>queso cheddar</ingrediente>
                <ingrediente>queso azul</ingrediente>
                <ingrediente>mozzarella</ingrediente>
                <ingrediente>champinon</ingrediente>
                <ingrediente>aceituna negra</ingrediente>
            </ingredientes>
            <masa tipoMasa="pan"/>
            <tamano tipoTamano="familiar"/>
            <foto tipoFoto="png"/>
            <link>www.thecreatorspizza.es/lostildaos</link>
        </pizza>
        <pizza codPizza="P06">
            <nombre>4 quesos</nombre> 
            <precio>10</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>queso parmesano</ingrediente>
                <ingrediente>queso cheddar</ingrediente>
                <ingrediente>queso azul</ingrediente>
                <ingrediente>mozzarella</ingrediente>
            </ingredientes>
            <masa tipoMasa="gruesa"/>
            <tamano tipoTamano="mediana"/>
            <foto tipoFoto="png"/>
            <link>www.thecreatorspizza.es/4quesos</link>
        </pizza>
        <pizza codPizza="P07">
            <nombre>barbacoa</nombre> 
            <precio>10</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>bacon</ingrediente>
                <ingrediente>carne</ingrediente>
                <ingrediente>mozzarella</ingrediente>
                <ingrediente>salsa barbacoa</ingrediente>
            </ingredientes>
            <masa tipoMasa="gruesa"/>
            <tamano tipoTamano="mediana"/>
            <foto tipoFoto="jpg"/>
            <link>www.thecreatorspizza.es/barbacoa</link>
        </pizza>
        <pizza codPizza="P08">
            <nombre>carbonara</nombre> 
            <precio>10</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>champinon</ingrediente>
                <ingrediente>mozzarella</ingrediente>
                <ingrediente>cebolla</ingrediente>
                <ingrediente>champinon</ingrediente>
            </ingredientes>
            <masa tipoMasa="gruesa"/>
            <tamano tipoTamano="mediana"/>
            <foto tipoFoto="png"/>
            <link>www.thecreatorspizza.es/carbonara</link>
        </pizza>
        <pizza codPizza="P09">
            <nombre>vegetal</nombre> 
            <precio>10</precio>
            <ingredientes>
                <ingrediente>tomate</ingrediente>
                <ingrediente>champinon</ingrediente>
                <ingrediente>aceiutuna</ingrediente>
                <ingrediente>mozzarella</ingrediente>
                <ingrediente>maiz</ingrediente>
                <ingrediente>cebolla</ingrediente>
                <ingrediente>esparragos</ingrediente>
            </ingredientes>
            <masa tipoMasa="gruesa"/>
            <tamano tipoTamano="mediana"/>
            <foto tipoFoto="png"/>
            <link>www.thecreatorspizza.es/vegetal</link>
        </pizza>
    </pizzas>
    <entrantes>
        <entrante>
            <nombre>Alitas de pollo</nombre>
            <precio>1.5</precio>
            <cantidad tipoCantidad="unidad">6</cantidad>
        </entrante>
        <entrante>
            <nombre>Nuggets</nombre>
            <precio>1</precio>
            <cantidad tipoCantidad="unidad">6</cantidad>
        </entrante>
        <entrante>
            <nombre>Patatas con bacon y queso</nombre>
            <precio>3</precio>
            <cantidad tipoCantidad="racion">1</cantidad>
        </entrante>
        <entrante>
            <nombre>Bolitas de queso</nombre>
            <precio>1.5</precio>
            <cantidad tipoCantidad="unidad">10</cantidad>
        </entrante>
        <entrante>
            <nombre>Ensalada</nombre>
            <precio>3</precio>
            <cantidad tipoCantidad="racion">1</cantidad>
        </entrante>
    </entrantes>    
    <postres>
        <postre codigoPostre="01">
            <nombre sabor="oreo">Cono helado</nombre>            
            <precio>2</precio>
        </postre>
        <postre codigoPostre="02">
            <nombre sabor="coockie">Tarrina de helado</nombre>
            <precio>1.5</precio>
        </postre>
        <postre codigoPostre="03">
            <nombre>Tarta de chocolate</nombre>
            <precio>2</precio>
        </postre>
        <postre codigoPostre="04">
            <nombre>Brownie</nombre>
            <precio>1</precio>
        </postre>
        <postre codigoPostre="05">
            <nombre sabor="kitkat">Sorbete de helado</nombre>
            <precio>2</precio>
        </postre>
        <postre codigoPostre="06">
            <nombre>Tarta de queso</nombre>
            <precio>2.5</precio>
        </postre>
    </postres>
    <bebidas>
        <refresco marcaRefresco="bitter_kas">
            <precio>1.5</precio>
            <cantidad>1</cantidad>
        </refresco> 
        <agua tipo="tiempo" tipoAgua="mineral">
            <precio>1</precio>
            <cantidad>2</cantidad>
        </agua>
        <cerveza marcaCerveza="keler" tipoCerveza="lagger">
            <precio>2.24</precio>
            <cantidad>5</cantidad>
        </cerveza>
    </bebidas>
</restaurante>
<!--
    -*-ATRIBUTOS Y VALORES-*-
    <PIZZAS>
        -General:
            -codPizza=P01,P02,P03,P04,P05,P06,P07,P08.
        -Masa:
            -tipoMasa=fina, gruesa, pan, cuadrada, rellena.
        -Tamano:
            -tipoTamano=pequena, mediana, familiar.
        -Foto:
            -tipoFoto=jpg, png.
    <ENTRANTES>
        Cantidad:
            -tipoCantidad:racion, unidad.
    <POSTRES>
        Nombre:
            /OPCIONAL\-sabor:oreo, coockie, kitkat, caramelo.
            -codigoPostre:01,02,03,04,05,06.
    <BEBIDAS>
        -General:
            tipo=frio, tiempo.
        -Agua:
            -tipoAgua=mineral, sin_gas, con_gas.
        -Cerveza: 
            -tipoCerveza=0.0, sin alcohol, normal, lagger.
            -marcaCerveza=paulaner, superboock, keler, heineken, mahou, estrella, amstel, corona, voll_damm, buckler.
        -Refrescos:
            -marcaRefresco=pepsi,cocacola, cocacola_ligth, kas_naranja, kas_limon, fanta_naranja, fanta_limon, 7up, nestea, aquarius, redbull, bitter_kas
    <MENUS>
        -Menu:
            -codigoMenu=01,02
-->
