=== elenaABSauces/Proyecto1920_LMSGI_EAB/1920_LMSGI_EAB/ud06/PizzeriaPasoFinal/public_html/datos/PizzeriaIngredientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listadoIngredientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="ingrediente"  maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elenaABSauces/Proyecto1920_LMSGI_EAB/1920_LMSGI_EAB/ud06/PizzeriaPasoFinal/public_html/datos/PizzeriaIngredientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<listadoIngredientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PizzeriaIngredientes.xsd">
    <ingrediente>tomate</ingrediente>
    <ingrediente>mozarella</ingrediente>
    <ingrediente>pina</ingrediente>
    <ingrediente>bacon</ingrediente>
    <ingrediente>aceituna verde</ingrediente>
    <ingrediente>aceituna negra</ingrediente>
    <ingrediente>salsa barbacoa</ingrediente>
    <ingrediente>carne</ingrediente>
    <ingrediente>queso cheddar</ingrediente>
    <ingrediente>atun</ingrediente>
    <ingrediente>maiz</ingrediente>
    <ingrediente>champinon</ingrediente>
    <ingrediente>queso parmesano</ingrediente>
    <ingrediente>queso azul</ingrediente>
    <ingrediente>esparragos</ingrediente>
    <ingrediente>cebolla</ingrediente>
</listadoIngredientes>
<!--
    LISTADO DE TODOS LOS INGREDIENTES DE LA CARTA.
-->
