=== elenaABSauces/Proyecto1920_LMSGI_EAB/1920_LMSGI_EAB/ud04/manualSchema.xsd
<?xml version="1.0"?>
<!--
Autor.- Elena de Anton
Fecha.- Martes 31 de marzo de 2020
Fichero.- manualSchema.xsd
Requerimientos.- 
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="manual">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="subtitulo" type="xs:string" minOccurs="0"/>
                <xs:element name="fecha_creacion">
                    <xs:simpleType>
                        <xs:restriction base="xs:date">
                            <xs:minExclusive value="2020-01-01"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="sistema">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="version" type="xs:float"/>
                                <xs:attribute name="tipo" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="url" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="pagina"/>
                            </xs:extension>
                        </xs:simpleContent>    
                    </xs:complexType>
                </xs:element>
                <xs:element name="paso" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="comando" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="codigo">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z]{3}[0-9]{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elenaABSauces/Proyecto1920_LMSGI_EAB/1920_LMSGI_EAB/ud05/examen ii marzo/manual.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Autor.- Elena de Anton
Fecha.- Martes 31 de marzo de 2020
Fichero.- manual.xml
Requerimientos.- 
-->
<!DOCTYPE manual [
<!ELEMENT manual (titulo,subtitulo?,fecha_creacion,sistema,url*,paso+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT fecha_creacion (#PCDATA)>
<!ELEMENT sistema (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT paso (comando,descripcion)>
<!ELEMENT comando (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

<!ATTLIST manual codigo CDATA #REQUIRED>
<!ATTLIST sistema version CDATA #REQUIRED>
<!ATTLIST sistema tipo (x64|x84) #REQUIRED>
<!ATTLIST url pagina CDATA #IMPLIED>
<!ATTLIST manual xmlns:xsi CDATA #IMPLIED>
<!ATTLIST manual xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
]>


<manual codigo="UBU18" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="manualSchema.xsd">
    
    <titulo>Servidor de Ubuntu</titulo>
    <subtitulo>Manual de instalación y configuración de Apache2</subtitulo>
    <fecha_creacion>2020-03-31</fecha_creacion>
    <sistema version="18.04" tipo="x64">Ubuntu</sistema>
    <url pagina="oficial">ubuntu</url>
    <url pagina="wiki">wikiubuntu</url>
    <paso>
        <comando>sudo apt update</comando>
        <descripcion>actualizacion del repositorio</descripcion>
    </paso>
    <paso>
        <comando>sudo apt install apache2</comando>
        <descripcion>Instalacion del servidor HTTP Apache2</descripcion>
    </paso>
    <paso>
        <comando>sudo service apache2 status</comando>
        <descripcion>Comprobacion del estado del servicio</descripcion>
    </paso>
    <paso>
        <comando>sudo adduser --home /var /www /html --group www-data operadorweb</comando>
        <descripcion>Comprobacion del estado del servicio</descripcion>
    </paso>
    <paso>
        <comando>sudo chmod -R 2775 /var/www/html</comando>
        <descripcion>Cambiar los permisos de forma recursiva al directorio html, de forma qu eel usuario tenga todos los permisos, el grupo tenga todos los permisos y el resto lectura y ejecucion</descripcion>
    </paso>
    <paso>
        <comando>sudo chawn -R operadorweb:www-data /var /www/html</comando>
        <descripcion>Cambiar el propietario de la carpeta html</descripcion>
    </paso>
</manual>
