<?xml version="1.0" encoding="UTF-8" standalone="no"?>
 <!DOCTYPE mail [  
	<!-- <!ELEMENT remitente (#PCDATA)> 
	<!-- <!ELEMENT asunto (#PCDATA)> 
	<!ELEMENT fecha (#PCDATA)> 
	<!ELEMENT correo (#PCDATA)> 
	<!ELEMENT mensaje (#PCDATA)> 
	<!ELEMENT tipo (#PCDATA)> 
	<!ELEMENT nombre (#PCDATA)> 
	<!ELEMENT image (tipo,nombre)> 
	<!ELEMENT destinatarios (correo+)>  
	<!ELEMENT adjuntar (image+)>  
	<!ATTLIST mail xmlns:xsi CDATA #IMPLIED>  
	<!ATTLIST mail xsi:noNamespaceSchemaLocation CDATA #IMPLIED>  
	<!ELEMENT mail (remitente?,asunto?,fecha?,destinatarios?,mensaje?,adjuntar?)>  
]>  
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SchemaXML01.xsd">
	<remitente>micorreo@correo.es</remitente>
	<asunto>Enviar un mensaje</asunto>
	<fecha>2020-01-14</fecha>
	<destinatarios>
		<correo>sucorreo@correo.es</correo>
		<correo>otrocorreo@correo.es</correo>
	</destinatarios>
	<mensaje>Solo tengo que enviarte un mensaje</mensaje>
	<adjuntar>
		<image>
			<tipo>imagen.png</tipo>
			<nombre>foto1.png</nombre>
		</image>	
		
		<image>
			<tipo>imagen.png</tipo>
			<nombre>foto2.png</nombre>
		</image>
	</adjuntar>
</mail>